#
#  Main API host (default)
#
timeout.connection=30

#
#  Named hosts (optional)
#  Used via: ApiClientProvider.get("auth"), get("payment")
#
 hosts.test=https://jsonplaceholder.typicode.com
# hosts.payment=https://pay.example.com

#
#  SSL certificates (optional)
#
# ssl.keyStore=certs/TESTclient.p12
# ssl.keyStorePassword=keypass
# ssl.trustStore=certs/TESTtruststore.p12
# ssl.trustStorePassword=trustpass